version: "3"

services:
  web:
    image: node:alpine
    ports:
      - "3000:3000"
    volumes:
      - /tmp:/serve
    command: /bin/sh -c 'wget https://raw.githubusercontent.com/nickgrealy/quick-serve/main/src/index.js && node index.js'
    restart: unless-stopped
