version: "3"

services:
  web:
    image: node
    ports:
      - "3000:3000"
    volumes:
      - /tmp:/serve
    command: |
      /bin/sh -c 'wget -O index.js https://raw.githubusercontent.com/nickgrealy/quick-serve/main/src/index.js \
        && wget -O package.json https://raw.githubusercontent.com/nickgrealy/quick-serve/main/package.json \
        && NODE_ENV=production npm install --omit=dev \
        && node index.js'
    restart: unless-stopped
